
- schemaLabel: Requirements
	schemaURL: Requirements.shex
	dataLabel: Requirements-example2
	dataURL: Requirements-example2.ttl
	queryMap: "{FOCUS a fhir:Requirements}@<Requirements>"
	status: conformant

- schemaLabel: Requirements
	schemaURL: Requirements.shex
	dataLabel: Requirements-example1
	dataURL: Requirements-example1.ttl
	queryMap: "{FOCUS a fhir:Requirements}@<Requirements>"
	status: conformant
